### ISSUE TITLE
"White screen" when shifting type writing

### ISSUE THREAD

**Issue by Shihang777** [UNNC-CS-GRP-DTGroup/GRP_V2.0#5]
When using new appearance, if user changes type writing method, the interface will be entirely white color without any button, label...

**Comment by PAN001** [comment]
This bug results from a bug in JTextField, as explained below:
http://stackoverflow.com/questions/14374111/input-method-removes-transparent-effect-from-jframe-in-swing
Done. Fix the bug by creating a subclass of JTextField and overriding paintComponent method.
